### ISSUE TITLE
demo app doesn't build

### ISSUE THREAD

**Issue by BigAppsAndroid1** [Mantano/iridium#83]
try to build demo app "as is" in emulator iPhone 14 Pro Max without success.

```
Failed to build iOS app
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/preload_page_view-0.1.6/lib/preload_page_view.dart:179:15: Error: The method 'PageMetrics.copyWith' doesn't have the named parameter 'devicePixelRatio' of overridden method 'Object with ScrollMetrics.copyWith'.
```

**Comment by Damianoux** [comment]
I can confirm that the problem occours when upgrading from 3.7.12 to 3.10.
The devicePixelRatio parameter is now required.
Maybe some of the libraries used need to be updated.
A quick fix is to downgrade to 3.7.12. go to the directory wehe flutter is  installed and run "git checkout 3.7.12".

**Comment by jmgeffroy** [comment]
Hi @Damianoux, Yes, absolutely. I have started migrating to Flutter 3.10, which implies migrating to Dart 3. Since many parts of Iridium depend on [dfunc](https://github.com/ookami-kb/dfunc), we must migrate the use of Product (--> D3 records), Coproduct (--> D3 sealed classes), and Either (--> D3 sealed classes + pattern matching). Work in progress.
See https://github.com/ookami-kb/dfunc/pull/25 and https://github.com/ookami-kb/dfunc/pull/25/commits

**Comment by jmgeffroy** [comment]
[Dart 3 Migration](https://github.com/Mantano/iridium/pull/84) complete.
